version: '3'

services:
  express-server:
    container_name: express-server
    hostname: backend
    build: ./server/
    ports:
      - "3000:3000"

  psql-server:
    container_name: psql-server
    hostname: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - psql-volume:/var/lib/postgresql/data
    networks:
      - fullstack

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin-server
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - psql-server
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - fullstack

volumes:
  psql-volume:


networks:
  fullstack:
    driver: bridge
